
import Head from "next/head";
import NavBar from "@/components/navbar/NavBar";
import FeedbackBar from "@/components/feedBackBar/FeedbackBar";

export default function Home() {

  return (
    <>
      <Head>
        <title>Feedback app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="lg:flex  gap-2 pt-4">
        <NavBar />
        <FeedbackBar />
      </div>

    </>
  );
}
